context:
  version: "10.4.9"

package:
  name: nestjs-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@nestjs/cli/-/cli-${{ version }}.tgz
  sha256: b3c4b18301fdae8f841908afa2b9e7728b397b58a0f5fc0931c6ed5c93a8a295

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - nest --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Nest - modern, fast, powerful node.js web framework (@cli)
  homepage: https://github.com/nestjs/nest-cli
  repository: https://github.com/nestjs/nest-cli

extra:
  recipe-maintainers:
    - danielnachun
