context:
  version: "12.0.7"

package:
  name: nestjs-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@nestjs/cli/-/cli-${{ version }}.tgz
  sha256: 7865ec962781996b7214f09fdff8b32d9947dd532588c2005e9c89dc659a5d91

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - nest --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Nest - modern, fast, powerful node.js web framework (@cli)
  homepage: https://github.com/nestjs/nest-cli
  repository: https://github.com/nestjs/nest-cli

extra:
  recipe-maintainers:
    - danielnachun
