context:
  version: "11.0.4"

package:
  name: nestjs-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@nestjs/cli/-/cli-${{ version }}.tgz
  sha256: 0537b04161b2ab37d1b4793881778fcb7663f0e3109613bd35115b0a8a71d6bd

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - nest --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Nest - modern, fast, powerful node.js web framework (@cli)
  homepage: https://github.com/nestjs/nest-cli
  repository: https://github.com/nestjs/nest-cli

extra:
  recipe-maintainers:
    - danielnachun
