context:
  version: "12.0.8"

package:
  name: nestjs-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@nestjs/cli/-/cli-${{ version }}.tgz
  sha256: beff4d8e4fd8cba594e8443f46160a170b31eab6018f700b20dd99b4133473df

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - nest --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Nest - modern, fast, powerful node.js web framework (@cli)
  homepage: https://github.com/nestjs/nest-cli
  repository: https://github.com/nestjs/nest-cli

extra:
  recipe-maintainers:
    - danielnachun
